// GENERATED by ingest/src/geo.mjs — do not edit by hand.
// World: union-square-sf
// Regenerate with: node ingest/bin/ingest.mjs build union-square-sf
export const ORIGIN_LAT = 37.787935;
export const ORIGIN_LON = -122.40752;
export const ORIGIN_ELEVATION_M = 23.94;
export const GRID_BEARING_DEG = 80.686;
export const LAT0_DEG = 37.788;
export const M_PER_DEG_LAT = 110992.476;
export const M_PER_DEG_LON = 88084.677;
export const BBOX_WGS84 = {"south":37.785,"west":-122.4115,"north":37.791,"east":-122.4035} as const;
