/**
 * geo.mjs — the single source of truth for every world's local coordinate frame.
 *
 * Before this module the same equirectangular projection was written out four times
 * (union-square-sf/src/geo/geo.ts, union-square-sf/tools/geo/build_gis.mjs, and the
 * frozen numbers inside kyoto-higashiyama/src/data/{geo.json,route.js}), each with
 * its own hand-copied metres-per-degree constants. They agreed, but nothing enforced
 * it — build_gis.mjs could only *warn* about drift. Here the constants are derived
 * from the world manifest and `emitRuntimeModule()` generates the runtime's copy, so
 * the two cannot disagree by construction.
 *
 * FRAME (right-handed, y-up, Three.js convention, metres):
 *   x = grid-east   : true bearing `gridBearingDeg`
 *   y = up          : metres relative to the origin's ground elevation
 *   z = grid-south  : true bearing `gridBearingDeg + 90`
 * A world with `gridBearingDeg: 90` gets the plain +X=east / +Z=south frame that
 * kyoto-higashiyama uses; union-square-sf rotates to the downtown street grid.
 */

const D2R = Math.PI / 180;

/**
 * Metres per degree of latitude/longitude at `latDeg`, from the standard WGS84
 * series expansion (Snyder / NGS). Scale error stays under a centimetre across a
 * +/-400 m working area, which is what a walkable twin needs.
 */
export function metresPerDegree(latDeg) {
  const phi = latDeg * D2R;
  return {
    lat: 111132.954 - 559.822 * Math.cos(2 * phi) + 1.175 * Math.cos(4 * phi),
    lon: 111412.84 * Math.cos(phi) - 93.5 * Math.cos(3 * phi) + 0.118 * Math.cos(5 * phi),
  };
}

/** Build the projection functions for one world's `frame` manifest block. */
export function createFrame(frame) {
  const {
    originLat,
    originLon,
    originElevationM = 0,
    gridBearingDeg = 90,
    lat0Deg = originLat,
  } = frame;
  const { lat: mLat, lon: mLon } = metresPerDegree(lat0Deg);
  const sinB = Math.sin(gridBearingDeg * D2R);
  const cosB = Math.cos(gridBearingDeg * D2R);

  /** WGS84 -> local. `elev` is metres in the world's vertical datum; omit for y = 0. */
  function geoToLocal(lat, lon, elev) {
    const dE = (lon - originLon) * mLon; // metres true-east of origin
    const dN = (lat - originLat) * mLat; // metres true-north of origin
    // grid-east unit vector in (E,N) is (sinB, cosB); grid-north is (-cosB, sinB).
    // z is grid-SOUTH, hence the negation of the grid-north component.
    return {
      x: dE * sinB + dN * cosB,
      y: elev === undefined ? 0 : elev - originElevationM,
      z: -(-dE * cosB + dN * sinB),
    };
  }

  /** Local -> WGS84. Exact inverse of geoToLocal (the 2x2 rotation is orthonormal). */
  function localToGeo(x, z) {
    const gridNorth = -z;
    const dE = x * sinB - gridNorth * cosB;
    const dN = x * cosB + gridNorth * sinB;
    return { lat: originLat + dN / mLat, lon: originLon + dE / mLon };
  }

  const inBbox = (bbox, lat, lon, marginM = 0) => {
    const dlat = marginM / mLat;
    const dlon = marginM / mLon;
    return (
      lat >= bbox.south - dlat && lat <= bbox.north + dlat &&
      lon >= bbox.west - dlon && lon <= bbox.east + dlon
    );
  };

  return { ...frame, metresPerDegLat: mLat, metresPerDegLon: mLon, geoToLocal, localToGeo, inBbox };
}

/**
 * Generate the runtime's frame constants as a source file, so the app and the
 * ingest pipeline are provably using the same numbers. Written by `ingest build`;
 * the world's own geo module imports from it instead of restating them.
 */
export function emitRuntimeModule(world, { lang = 'ts' } = {}) {
  const f = createFrame(world.frame);
  const asConst = lang === 'ts' ? ' as const' : '';
  const n = (v, dp) => Number(v.toFixed(dp));
  return `// GENERATED by ingest/src/geo.mjs — do not edit by hand.
// World: ${world.id}
// Regenerate with: node ingest/bin/ingest.mjs build ${world.id}
export const ORIGIN_LAT = ${world.frame.originLat};
export const ORIGIN_LON = ${world.frame.originLon};
export const ORIGIN_ELEVATION_M = ${world.frame.originElevationM ?? 0};
export const GRID_BEARING_DEG = ${world.frame.gridBearingDeg ?? 90};
export const LAT0_DEG = ${world.frame.lat0Deg ?? world.frame.originLat};
export const M_PER_DEG_LAT = ${n(f.metresPerDegLat, 3)};
export const M_PER_DEG_LON = ${n(f.metresPerDegLon, 3)};
export const BBOX_WGS84 = ${JSON.stringify(world.bbox)}${asConst};
`;
}
