/**
 * licenses.mjs — what each upstream dataset actually permits, and what that means
 * for a repo whose own code is MIT.
 *
 * The root README already says the right thing in prose ("Geometry is derived from
 * OpenStreetMap (ODbL) and USGS 3DEP (public domain)"). This turns that prose into
 * a gate: every ingested feature carries the id of the source it came from, and
 * `ingest verify` fails if a feature's licence is unknown, if a non-redistributable
 * source contributed shipped bytes, or if a required attribution never reaches the
 * generated ATTRIBUTION.md.
 *
 * The distinction that matters is SHARE-ALIKE vs PERMISSIVE. ODbL share-alike runs
 * with the *database*, not with the rendering code, which is why the runtime ships
 * under MIT while the derived database stays ODbL — but only as long as the
 * attribution actually ships. Hence `requiresAttribution`.
 */

/** @typedef {'public-domain'|'permissive'|'share-alike'|'restricted'} LicenceClass */

export const LICENSES = {
  'ODbL-1.0': {
    class: 'share-alike',
    name: 'Open Database License 1.0',
    url: 'https://opendatacommons.org/licenses/odbl/1-0/',
    requiresAttribution: true,
    redistributable: true,
  },
  'CC-BY-4.0': {
    class: 'permissive',
    name: 'Creative Commons Attribution 4.0',
    url: 'https://creativecommons.org/licenses/by/4.0/',
    requiresAttribution: true,
    redistributable: true,
  },
  'CC-BY-SA-4.0': {
    class: 'share-alike',
    name: 'Creative Commons Attribution-ShareAlike 4.0',
    url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    requiresAttribution: true,
    redistributable: true,
  },
  'CC0-1.0': {
    class: 'public-domain',
    name: 'Creative Commons Zero 1.0',
    url: 'https://creativecommons.org/publicdomain/zero/1.0/',
    requiresAttribution: false,
    redistributable: true,
  },
  'US-PD': {
    class: 'public-domain',
    name: 'US Government work, public domain',
    url: 'https://www.usa.gov/government-works',
    requiresAttribution: false,
    redistributable: true,
  },
  'JP-GOV-2.0': {
    class: 'permissive',
    name: 'Japan Government Standard Terms of Use 2.0 (CC-BY-4.0 compatible)',
    url: 'https://www.mlit.go.jp/plateau/site-policy/',
    requiresAttribution: true,
    redistributable: true,
  },
  'PROPRIETARY-REFERENCE-ONLY': {
    class: 'restricted',
    name: 'Proprietary — may be consulted as a visual reference, never redistributed',
    url: null,
    requiresAttribution: true,
    redistributable: false,
  },
};

/**
 * Licences whose data may be baked into a shipped world. Everything else is
 * reference-only: an agent may look at it to decide a number, but the bytes must
 * not land in the repo. Google Earth / Street View sit in that second bucket, which
 * is exactly the constraint union-square-sf/PROMPT.md states in prose.
 */
export const REDISTRIBUTABLE = Object.entries(LICENSES)
  .filter(([, l]) => l.redistributable)
  .map(([id]) => id);

export function assertKnownLicense(id) {
  if (!LICENSES[id]) {
    throw new Error(
      `unknown license id "${id}". Add it to ingest/src/licenses.mjs with an explicit ` +
        'redistributable flag before any adapter claims it.',
    );
  }
  return LICENSES[id];
}

/** Render the ATTRIBUTION.md that every world ships if it uses attributed sources. */
export function renderAttribution(worldId, usedSources) {
  const lines = [
    `# Data attribution — ${worldId}`,
    '',
    `GENERATED by \`node ingest/bin/ingest.mjs build ${worldId}\`. Do not edit by hand.`,
    '',
    'This world is assembled from the public datasets below. Each entry is the licence',
    'the upstream publisher actually applies; the derived database in this repository',
    'inherits the most restrictive of them.',
    '',
    '| Source | Dataset | Licence | Attribution |',
    '|---|---|---|---|',
  ];
  for (const s of usedSources) {
    const lic = LICENSES[s.license];
    const licCell = lic?.url ? `[${lic.name}](${lic.url})` : (lic?.name ?? s.license);
    lines.push(`| \`${s.id}\` | ${s.title} | ${licCell} | ${s.attribution} |`);
  }
  const shareAlike = usedSources.filter((s) => LICENSES[s.license]?.class === 'share-alike');
  if (shareAlike.length) {
    lines.push(
      '',
      '## Share-alike notice',
      '',
      'The sources below are share-alike. The **derived database** in this world',
      '(footprints, street centrelines, elevations, place records) is therefore itself',
      'share-alike; the rendering code around it remains MIT.',
      '',
      ...shareAlike.map((s) => `- ${s.attribution} — ${LICENSES[s.license].name}`),
    );
  }
  const restricted = usedSources.filter((s) => LICENSES[s.license]?.class === 'restricted');
  if (restricted.length) {
    lines.push(
      '',
      '## Reference-only sources',
      '',
      'Consulted during reconstruction. No bytes from these sources are redistributed here;',
      'they informed measurements that were then reproduced procedurally.',
      '',
      ...restricted.map((s) => `- ${s.title} — ${s.attribution}`),
    );
  }
  return lines.join('\n') + '\n';
}
