/**
 * provenance.mjs — every number in a world can name where it came from.
 *
 * The Higashiyama survey overturned six widely-repeated figures (the Yasaka Pagoda
 * is 38.79 m, not 46; the Kiyomizu stage deck is at 115.5 m ASL, not 240). That
 * result is only defensible because a human wrote the sources down by hand in
 * docs/recon/*.md. This module makes the same rigour mechanical: an ingested value
 * is a `Fact`, a Fact without a source is a build error, and two Facts that
 * disagree about the same measurement become a `Conflict` an agent must resolve
 * rather than silently averaging away.
 */

/**
 * @typedef {object} Fact
 * @property {*}      value        the measurement itself
 * @property {string} unit         'm' | 'deg' | 'count' | 'text' | ...
 * @property {string} sourceId     id of the adapter that produced it
 * @property {string} license      SPDX-ish id from licenses.mjs
 * @property {string} fetchedUtc   ISO-8601, e.g. '2026-09-03T00:00:00Z'
 * @property {'high'|'medium'|'low'} confidence
 * @property {string} [note]       why this value, or what makes it uncertain
 * @property {string} [ref]        upstream identifier: OSM way id, Wikidata QID, ...
 */

/** @returns {Fact} */
export function fact(value, { unit = 'text', sourceId, license, fetchedUtc, confidence = 'medium', note, ref }) {
  if (!sourceId) throw new Error('fact() requires sourceId — an unsourced value is a build error');
  if (!license) throw new Error(`fact() from "${sourceId}" requires a license id`);
  return {
    value, unit, sourceId, license,
    fetchedUtc: fetchedUtc ?? new Date().toISOString(),
    confidence, ...(note ? { note } : {}), ...(ref ? { ref } : {}),
  };
}

const CONFIDENCE_RANK = { high: 3, medium: 2, low: 1 };

/**
 * Reconcile several Facts about the same measurement.
 *
 * Deliberately does NOT average. Averaging a correct survey figure with a
 * repeated-everywhere wrong one is how "the pagoda is 42 m" happens. Instead the
 * highest-confidence Fact wins, and anything materially disagreeing with it is
 * recorded as a conflict for a human or an agent to adjudicate.
 *
 * @param {Fact[]} facts
 * @param {object} [opts]
 * @param {number} [opts.toleranceRel=0.02]  relative disagreement treated as agreement
 * @returns {{chosen: Fact, conflicts: Array<{rejected: Fact, deltaRel: number}>}}
 */
export function reconcile(facts, { toleranceRel = 0.02 } = {}) {
  if (!facts?.length) throw new Error('reconcile() needs at least one fact');
  const sorted = [...facts].sort((a, b) => CONFIDENCE_RANK[b.confidence] - CONFIDENCE_RANK[a.confidence]);
  const chosen = sorted[0];
  const conflicts = [];
  if (typeof chosen.value === 'number') {
    for (const f of sorted.slice(1)) {
      if (typeof f.value !== 'number') continue;
      const denom = Math.abs(chosen.value) || 1;
      const deltaRel = Math.abs(f.value - chosen.value) / denom;
      if (deltaRel > toleranceRel) conflicts.push({ rejected: f, deltaRel });
    }
  }
  return { chosen, conflicts };
}

/**
 * Render the uncertainty register a world ships alongside its data — the machine
 * equivalent of kyoto-higashiyama's "commonly stated vs measured" table.
 */
export function renderUncertaintyRegister(worldId, entries) {
  const lines = [
    `# Uncertainty register — ${worldId}`,
    '',
    `GENERATED by \`node ingest/bin/ingest.mjs build ${worldId}\`. Do not edit by hand.`,
    '',
    'Every measurement where two sources disagreed by more than the reconciliation',
    'tolerance. The chosen value is the one the world is built on.',
    '',
    '| Measurement | Chosen | Source | Rejected | Rejected source | Δ |',
    '|---|---|---|---|---|---|',
  ];
  let n = 0;
  for (const e of entries) {
    for (const c of e.conflicts) {
      n++;
      const pct = `${(c.deltaRel * 100).toFixed(1)} %`;
      lines.push(
        `| ${e.key} | ${e.chosen.value} ${e.chosen.unit} | \`${e.chosen.sourceId}\` | ` +
          `${c.rejected.value} ${c.rejected.unit} | \`${c.rejected.sourceId}\` | ${pct} |`,
      );
    }
  }
  if (n === 0) lines.push('| _(no conflicts recorded)_ | | | | | |');
  return lines.join('\n') + '\n';
}
