/**
 * refs.mjs — materialise camera-match reference photography from the manifest.
 *
 * The repo gitignores `refs/**\/*.jpg`, which is the right call — redistributing
 * other people's photographs is not this project's business, and the tree would
 * balloon. But it left the QA harness without ground truth on a fresh clone: the
 * comparison pass simply cannot run.
 *
 * The fix is to commit the *manifest* and fetch the pixels on demand. Filenames are
 * derived from the Commons title, so they are stable across runs, and every
 * downloaded image gets a sidecar carrying its licence and author — which is what
 * CC-BY-SA actually requires of anyone who redistributes a screenshot of the
 * comparison sheet.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { fetchBinary } from './http.mjs';

const safe = (s) => s.replace(/[^\w.-]+/g, '_').slice(0, 120);

/**
 * @param {string} repoRoot
 * @param {object} world      the world manifest
 * @param {Array}  refs       `referenceImages` from the built dataset
 * @param {object} [opts]
 * @param {number} [opts.perViewpoint=6]  cap per viewpoint; the manifest holds many more
 */
export async function downloadReferences(repoRoot, world, refs, opts = {}) {
  const { perViewpoint = 6, log = () => {} } = opts;
  const root = path.join(repoRoot, world.worldDir, 'refs');
  const cacheDir = path.join(repoRoot, '.ingest-cache', world.id, 'refs');

  const byViewpoint = new Map();
  for (const r of refs) {
    if (!byViewpoint.has(r.viewpointId)) byViewpoint.set(r.viewpointId, []);
    byViewpoint.get(r.viewpointId).push(r);
  }

  let written = 0, failed = 0;
  for (const [viewpointId, list] of byViewpoint) {
    const dir = path.join(root, safe(viewpointId));
    await fs.mkdir(dir, { recursive: true });

    // Prefer references whose recorded compass heading is known — those are the
    // ones a camera-match reviewer can actually align to. Then prefer larger
    // images, since a low-resolution reference cannot resolve bay rhythm.
    const ranked = [...list].sort((a, b) => {
      const h = (a.headingDeg != null ? 0 : 1) - (b.headingDeg != null ? 0 : 1);
      return h !== 0 ? h : (b.width ?? 0) - (a.width ?? 0);
    }).slice(0, perViewpoint);

    const sidecar = [];
    for (const ref of ranked) {
      const name = safe(ref.file);
      try {
        const r = await fetchBinary(ref.url, { cacheDir, maxAgeMs: Infinity, timeoutMs: 120_000 });
        await fs.writeFile(path.join(dir, name), r.buffer);
        written++;
        sidecar.push({
          file: name, title: ref.title, licence: ref.licence, licenceUrl: ref.licenceUrl,
          author: ref.author, headingDeg: ref.headingDeg, takenOn: ref.takenOn,
          descriptionUrl: ref.descriptionUrl, width: ref.width, height: ref.height,
        });
      } catch (err) {
        failed++;
        log(`  ${viewpointId}/${name}: ${err.message}`);
      }
    }
    await fs.writeFile(path.join(dir, 'SOURCES.json'), JSON.stringify(sidecar, null, 2));
    await fs.writeFile(path.join(dir, 'SOURCES.md'), renderSourcesMd(viewpointId, sidecar));
  }
  return { written, failed, viewpoints: byViewpoint.size };
}

function renderSourcesMd(viewpointId, entries) {
  const lines = [
    `# Reference photography — ${viewpointId}`,
    '',
    'GENERATED by `node ingest/bin/ingest.mjs refs <world>`. The images themselves are',
    'gitignored; this file is the record of what they are and who made them.',
    '',
    '| File | Licence | Author | Heading | Taken | Source |',
    '|---|---|---|---|---|---|',
  ];
  for (const e of entries) {
    lines.push(
      `| \`${e.file}\` | ${e.licence} | ${e.author ?? '—'} | ` +
        `${e.headingDeg != null ? `${e.headingDeg}°` : '—'} | ${e.takenOn ?? '—'} | ` +
        `[Commons](${e.descriptionUrl}) |`,
    );
  }
  if (!entries.length) lines.push('| _(none downloaded)_ | | | | | |');
  return lines.join('\n') + '\n';
}
