// GENERATED by ingest/src/geo.mjs — do not edit by hand.
// World: unc-davis-library
// Regenerate with: node ingest/bin/ingest.mjs build unc-davis-library
export const ORIGIN_LAT = 35.9109606;
export const ORIGIN_LON = -79.0478858;
export const ORIGIN_ELEVATION_M = 144.35;
export const GRID_BEARING_DEG = 97.405;
export const LAT0_DEG = 35.911;
export const M_PER_DEG_LAT = 110957.36;
export const M_PER_DEG_LON = 90264.856;
export const BBOX_WGS84 = {"south":35.9075,"west":-79.0525,"north":35.914,"east":-79.0435} as const;
